export const experienceData = [
  {
    orgName: 'MLH Fellowship',
    orgLink: 'https://fellowship.mlh.io',
    from: 'July 2022',
    to: 'August 2022',
    position: 'Prep Fellow',
    location: 'Remote',
    desc: 'Revamped the website',
    workDone: [
      'An internship alternative program in which I collaborated with people from all over the world on open-source projects',
      'Made contributions to portfolio project made with Jekyll (https://mlh-fellowship.github.io/prep-portfolio-22.AUG.PREP.2/)',
      'Made contributions to a weather app made with React (https://mlh-fellowship.github.io/prep-project-22.AUG.PREP.2/)',
    ],
  },
  {
    orgName: 'SaffronStays',
    orgLink: 'https://saffronstays.com',
    from: 'June 2021',
    to: 'June 2022',
    position: 'Web Development Intern',
    location: 'Remote',
    desc: 'Revamped the website',
    workDone: [
      'Online travel agency with 50k daily visitors; part of a team to renovate website using the React ecosystem',
      'Created an easy-to-use dashboard for stakeholders',
      'Implemented JWT auth, reusable components for use across the website',
      'Reprogrammed APIs from Node to Golang for better performance and latency',
    ],
  },
  {
    orgName: 'Artistan',
    orgLink: '',
    from: 'April 2021',
    to: 'June 2021',
    position: 'Frontend Intern',
    location: 'Remote',
    desc: 'Revamped the website',
    workDone: [
      'Developed a responsive PWA for an e-commerce store from scratch using React',
      'Implemented OTP-based authentication system using JWT, including Google and Facebook logins',
      'Created an autosaving form using Formik, with reordering-enabled image gallery for user input ',
    ],
  },
];
